apiVersion: apps/v1
kind: Deployment 
metadata:
  name: notification-service-deployment
  namespace: secureflow
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      serviceAccountName: notification-service-sa
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: notification-service
          image: 066606187609.dkr.ecr.ap-south-1.amazonaws.com/secureflow/notification-service:latest
          imagePullPolicy: Always 
          ports:
            - containerPort: 8004
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 15
            periodSeconds: 10