pipeline {
    agent any 

    // def getServices() {
    //     return [
    //     [name: 'api-gateway', dir: 'api-gateway'],
    //     [name: 'user-service', dir: 'user-services'],
    //     [name: 'product-service', dir: 'product-services'],
    //     [name: 'order-service', dir: 'order-services'],
    //     [name: 'notification-service', dir: 'notification-services']
    // ]
    // }

    environment {
        AWS_REGION      =   "ap-south-1"
        ECR_REGISTRY    =   "066606187609.dkr.ecr.ap-south-1.amazonaws.com"
        PROJECT_NAME    =   "secureflow"
        APP_SERVER_IP   =   "10.0.1.235"
        CLUSTER_NAME    =   "secureflow"
        APP_HOME        =   "/home/ubuntu/SecureFlow"
    }

    stages {

        stage('Cleanup Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
                echo "Code checked out from ${env.GIT_BRANCH}"
            }
        }

        stage('Bandit') {
            steps {
                sh '''
                  export PATH=$PATH:/var/lib/jenkins/.local/bin
                  pip3 install bandit --quiet
                  echo "Running Bandit scan"

                  bandit -r services/ -f json -o bandit-report.json --severity-level medium || true

                  echo "Bandit scan complete"
                '''
            }

            post {
                always {
                    archiveArtifacts artifacts: 'bandit-report.json', allowEmptyArchive: true
                }
            }
        }

        stage('Gitleaks Secret Scan') {
         steps {
            sh '''
              echo "Running Gitleaks secret scan..."

              # Create a local directory in jenkins workspace
              mkdir -p $HOME/bin


              #Install gitleaks if not present

              if ! command -v gitleaks &> /dev/null; then
                echo "Installing gitleaks..."

                curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz \
                | tar -xz -C $HOME/bin gitleaks
                
                chmod +x $HOME/bin/gitleaks
              fi

               export PATH="$HOME/bin/:$PATH"

               gitleaks detect --source . --report-format json --report-path gitleaks-report.json --exit-code 1
            '''
        }

        post {
            always {
                archiveArtifacts artifacts: 'gitleaks-report.json', allowEmptyArchive: true
            }

            failure {
                error "Gitleaks found secret in codebase. Pipeline stopped"
            }
        }
    }

        stage('Safety Dependency Scan') {
        steps {
            sh '''
              pip3 install --user "safety==2.3.5" --quiet
              export PATH=$PATH:$(python3 -m site --user-base)/bin

              echo "Running safety dependency scan"

              for service in user-services product-services order-services api-gateway notification-services; do
                echo "Scanning $service dependencies..."
                
                python3 -m safety check -r services/$service/requirements.txt --output json > safety-$service-report.json || true
              done

              echo "Dependency scan complete"
            '''
        }

        post {
            always {
                archiveArtifacts artifacts: 'safety-*-report.json', allowEmptyArchive: true
            }
        }
    }

        stage('Docker Build') {
        steps {
                script {
                    def services = [
                        'api-gateway',
                        'user-service',
                        'product-service',
                        'order-service',
                        'notification-service'
                    ]

                    def serviceDirs = [
                        'api-gateway'          : 'api-gateway',
                        'user-service'         : 'user-services',
                        'product-service'      : 'product-services',
                        'order-service'        : 'order-services',
                        'notification-service' : 'notification-services'
                    ]

                    env.GIT_SHA = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                    echo "Building images with tag: ${env.GIT_SHA}"
                    sh "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 066606187609.dkr.ecr.ap-south-1.amazonaws.com"

                    services.each { service ->
                        def dir = serviceDirs[service]
                        sh """
                            docker build \
                                -t ${ECR_REGISTRY}/${PROJECT_NAME}/${service}:${env.GIT_SHA} \
                                -t ${ECR_REGISTRY}/${PROJECT_NAME}/${service}:latest \
                                ./services/${dir}
                        """
                        echo "Built ${service}"
                    }
                }
            }
    }

        stage('Trivy Scan Image') {
        steps {
            script {
                def services = [
                        'api-gateway',
                        'user-service',
                        'product-service',
                        'order-service',
                        'notification-service'
                    ]

                // Install trivy if not present
                sh '''
                  mkdir -p "$HOME/bin"

                  if ! command -v trivy &> /dev/null; then
                    echo "Installing Trivy..."
                            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
                                | sh -s -- -b "$HOME/bin"
                  fi

                  export PATH="$HOME/bin:$PATH"
                  trivy --version
                '''

                services.each { service ->
                        sh """
                            export PATH="\$HOME/bin:\$PATH"

                            echo "Scanning ${service}..."

                            trivy image \
                                --quiet \
                                --format json \
                                --output trivy-${service}-report.json \
                                --severity LOW,MEDIUM,HIGH,CRITICAL \
                                --exit-code 0 \
                                ${ECR_REGISTRY}/${PROJECT_NAME}/${service}:${env.GIT_SHA}

                            echo "${service} passed Trivy scan"
                        """
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'trivy-*-report.json', allowEmptyArchive: true

        }
        
        }
    }

        stage('Push to ECR') {
        steps {
            script {
                sh """
                  echo "Login to ECR"

                  aws ecr get-login-password --region ${AWS_REGION} | \
                  docker login --username AWS --password-stdin ${ECR_REGISTRY}
                """

                def services = [
                            'api-gateway',
                            'user-service',
                            'product-service',
                            'order-service',
                            'notification-service'
                        ]

                services.each { service ->
                            sh """
                                echo "Pushing ${service}..."
                                docker push ${ECR_REGISTRY}/${PROJECT_NAME}/${service}:${env.GIT_SHA}
                                docker push ${ECR_REGISTRY}/${PROJECT_NAME}/${service}:latest
                                echo "Pushed ${service}"
                            """
                }
            }
        }
    }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    withCredentials([sshUserPrivateKey(
                        credentialsId: 'app-server-ssh',
                        keyFileVariable: 'SSH_KEY',
                        usernameVariable: 'SSH_USER'
                        ),
                        file(credentialsId: 'app-secrets-file', variable: 'APP_SECRETS'),
                        string(credentialsId: 'grafana-admin-password', variable: 'GRAFANA_PASSWORD')]) {
                            def gitSha = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                            def gitShaPattern = ":${gitSha}"
                            
                            // 1. LANDING ZONE: SCP to the home directory
                            sh '''
                              scp -i "${SSH_KEY}" -o StrictHostKeyChecking=no "${APP_SECRETS}" "${SSH_USER}@${APP_SERVER_IP}:/home/ubuntu/app-secrets.tmp"
                            '''

                            // 2. REMOTE LOGIC
                            sh """
ssh -i ${SSH_KEY} -o StrictHostKeyChecking=no ${SSH_USER}@${APP_SERVER_IP} << 'EOF'
set -e
                                    
# Check if directory exists. If not them clone it
if [ ! -d "/home/ubuntu/SecureFlow" ]; then
    echo "First time setup. Cloning the repo"
    git clone https://github.com/amandev-x/SecureFlow.git /home/ubuntu/SecureFlow
fi

cd /home/ubuntu/SecureFlow

# Pull the latest changes
git pull origin main 


# Image tag replacement
find k8s/ -name "deployment*.yml" -exec sed -i "s|:latest|:${gitShaPattern}|g" {} +

# Docker Login
aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}

# Apply k8s namespace
kubectl apply -f k8s/namespace.yml

# Create k8s secret
kubectl create secret generic app-secrets --from-file=app-secrets.yml=/home/ubuntu/app-secrets.tmp \
    -n secureflow --dry-run=client -o yaml | kubectl apply -f -

# Create K8s secret for docker login
kubectl create secret docker-registry ecr-secret --docker-server=${ECR_REGISTRY} \
    --docker-username=AWS --docker-password=\$(aws ecr get-login-password --region ${AWS_REGION}) \
    -n secureflow --dry-run=client -o yaml | kubectl apply -f -

# Apply all manifests
kubectl apply -f k8s/rbac/
kubectl apply -f k8s/network-policies/

# Apply all services
kubectl apply -f k8s/user-service
kubectl apply -f k8s/product-service
kubectl apply -f k8s/order-service
kubectl apply -f k8s/notification-service
kubectl apply -f k8s/api-gateway
kubectl apply -f k8s/ingress.yml

# Ensure nginx ingress is installed
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx || true
helm repo update

# install if not exists, skip if already installed
helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
    --namespace ingress-nginx --create-namespace \
    --set controller.service.type=NodePort \
    --set controller.service.nodePorts.http=30000 \
    --set controller.service.nodePorts.https=30001 \
    --wait || true

# Ensure monitoring is installed
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts || true
helm repo update

helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
    --namespace monitoring --create-namespace --values k8s/monitoring/prometheus-values.yml \
    --set grafana.adminPassword=\${GRAFANA_PASSWORD} \
    --wait || true

# Smart rollback
for deploy in user-service product-service order-service notification-service api-gateway; do
    kubectl rollout status deployment/\${deploy}-deployment -n secureflow --timeout=120s
done

echo "Deployment of ${gitShaPattern} completed successfully!"
find k8s/ -name "deployment*.yml" -exec sed -i "s|:${gitShaPattern}|:latest|g" {} +


echo "Cleaning up old Docker images on App Server..."
docker image rmi \$(docker images -q) || true
docker system prune -f || true


echo "Deleting app-secrets.tmp"
rm -f /home/ubuntu/app-secrets.tmp
EOF
"""
                        }
                    }
            }
            post {
                failure {
                    echo "Deployment to Kubernetes failed"
                }
                success {
                    echo "Successfully deployed to Kubernetes"
                }
            }
        }

        stage('Health Check') {
            steps {
                sh """
                  echo "🔍 Running health checks..."
                  sleep 10

                  for i in 1 2 3 4 5; do 
                    STATUS=\$(curl -s -o /dev/null -w "%{http_code}" http://${APP_SERVER_IP}/health)

                    if [ "\$STATUS" = "200" ]; then 
                      echo "Health check passed. Api gateway is up"
                      exit 0
                    fi 

                    echo "Attempt \$i failed (status: \$STATUS), retrying in 10s..."
                    sleep 5
                  done

                  echo "Health check failed after 5 attempts"
                  exit 1
                """
            }
        }
    }


// ── Post Pipeline ──────────────────────────────────────────────────────
post {
    success {
        echo """
            Pipeline completed successfully!
            ─────────────────────────────────
            Branch  : ${env.GIT_BRANCH}
            Commit  : ${env.GIT_SHA}
            App URL : http://${APP_SERVER_IP}:8000
            """
            }
        
        failure {
            echo " Pipeline failed — check logs above"
        }
    }
}
